
###get all contacts local
GET http://localhost:3000/contacts

###get contact by id local

GET http://localhost:3000/contacts/626823f5808ee068d6b40756

###get all contacts heroku
GET https://cse341reece.herokuapp.com/contacts HTTP/1.1

###get contact by id heroku
GET https://cse341reece.herokuapp.com/contacts/626823f5808ee068d6b40756 HTTP/1.1

###create contact
POST https://cse341reece.herokuapp.com/contacts HTTP/1.1
content-type: application/json

{
  "fname": "Ron",
  "lname": "Swanson",
  "email": "example8@gmail.com",
  "phone": "555-555-5555",
  "bday": "september",
  "favcolor": "purple"
}

###Put contact local
PUT http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
  "fname": "Ron",
  "lname": "Swanson",
  "email": "example8@gmail.com",
  "phone": "555-555-5555",
  "bday": "september",
  "favcolor": "purple"
}

###Put contact
PUT https://cse341reece.herokuapp.com/contacts/627ad4d8b611396e68b042eb HTTP/1.1
content-type: application/json

{
  "fname": "Sam",
  "lname": "Reece",
  "email": "example69@gmail.com",
  "phone": "555-555-5555",
  "bday": "july",
  "favcolor": "purple"
}

###Delete contact 
DELETE https://cse341reece.herokuapp.com/contacts/627ad4d8b611396e68b042eb HTTP/1.1